#:kivy 1.0.9
#:import Gauge gauge

<Display>:
    spacing: 0
    orientation: 'vertical'
    gauge: gauge
    slider: slider
    canvas.before:
        Color:
            rgba: 1,1,1,.5
        Line:
            points: 0, 0, 10, 0
    Gauge:
        id: gauge
        width: 800
        height: 432
    Slider:
        id: slider
        width: 800
        on_value: root.set_gauge(value=self.value)
